"""Was added some variables to Albums model to db

Revision ID: 3371d0f0cec1
Revises: 955e5f67af14
Create Date: 2023-03-12 14:46:55.677208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3371d0f0cec1'
down_revision = '955e5f67af14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('released', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('genres', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('language')
        batch_op.drop_column('genres')
        batch_op.drop_column('released')

    # ### end Alembic commands ###
