"""Was added unnullable to db

Revision ID: 37450507422b
Revises: 3371d0f0cec1
Create Date: 2023-03-12 14:48:39.277415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37450507422b'
down_revision = '3371d0f0cec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('released',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('released',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
